### ISSUE TITLE
Create "Your First Laser Cut" article

### ISSUE THREAD

**Issue by kevinarne** [GIXLabs/GIXLabs.github.io#47]
I'd like to have a no-frills article that walks folks through how to use the laser cutters. The goal is to have a completely inexperienced person scan a QR code at the laser, then be able to walk through the process of using the Glowforge lasers without any external help.

In scope:
Uploading a file.
Selecting material from Glowforge presets.
Changing items from engraves to cuts to scores.
How the Glowforge separates the file into items.
Changing order of items.
Positioning artwork on material.
Two rules of laser cutting: don't leave cut unattended and talk to staff before using external materials.

Out of scope:
Design (they should cut a sample file we provide)
In-depth tutorial on Glowforge interface

**Comment by chuanisawesome** [comment]
Please check the document that I've uploaded.

**Comment by chuanisawesome** [comment]
@kevinarne, I've updated the doc.

**Comment by kevinarne** [comment]
This looks really good, I made a few minor tweaks, but am very pleased with it. Hoping to test it this week with some of the other staff.
