### ISSUE TITLE
Adjust Footer

### ISSUE THREAD

**Issue by kevinarne** [GIXLabs/GIXLabs.github.io#53]
Please add a footer to all pages that asks people to request new articles or correct dead links via the Issues page. I'm not entirely sure how to do this, but this page should help: https://just-the-docs.github.io/just-the-docs/docs/customization/#custom-footer

**Comment by chuanisawesome** [comment]
I have added _includes/footer_custom.html file that changes the footer for all pages, and now can be edited to the proper format.
