### ISSUE TITLE
Fix links on main page

### ISSUE THREAD

**Issue by kevinarne** [GIXLabs/GIXLabs.github.io#64]
Links to the bandsaw article and faster 3D prints article appear to be broken.

**Comment by chuanisawesome** [comment]
@kevinarne I am able to go to the bandsaw and faster 3D prints article, and I also checked the links in the bandsaw and it worked. Let me know what error you are getting.

**Comment by kevinarne** [comment]
I think I fixed it but forgot to close the issue. Thanks for checking and sorry about that!
